# Matriz

In [1]:
# Instanciando uma matriz 4x2 em um objeto do tipo list
matrix = [
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
]
matrix

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [2]:
# Indexando a matriz para acessar o elemento da primeira linha e primeira coluna
matrix[0][0]

1

In [3]:
# Indexando a matriz para acessar o elemento da primeira linha e segunda coluna
matrix[0][1]

2

# Dicionários multi classe

In [4]:
# Instanciando um dicionário para armazenar informações sobre a iluminação de um ambiente
locais = ['sala', 'cozinha', 'quarto', 'banheiro']
lampadas = ['ligada', 'desligada', 'quebrada', 'ligada']
num_lampdas = [2, 1, 1, 3]
testadas = [True, False, False, True]
metros_quadrados = [20.0, 15.2, 10.4, 5.9]

iluminação_1 = {
    'locais': locais,
    'lampadas': lampadas,
    'num_lampdas': num_lampdas,
    'testadas': testadas,
    'metros_quadrados': metros_quadrados
}
iluminação_1

{'locais': ['sala', 'cozinha', 'quarto', 'banheiro'],
 'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
 'num_lampdas': [2, 1, 1, 3],
 'testadas': [True, False, False, True],
 'metros_quadrados': [20.0, 15.2, 10.4, 5.9]}

In [5]:
# Instanciando um dicionário para armazenar informações sobre a iluminação de um ambiente, utilizando tuplas e conjuntos
locais = ('sala', 'cozinha', 'quarto', 'banheiro')
lampadas = ['ligada', 'desligada', 'quebrada', 'ligada']
num_lampdas = (2, 1, 1, 3)
testadas = {
            locais[0]: True, 
            locais[1]: False, 
            locais[2]: False, 
            locais[3]: True
}
metros_quadrados = {20.0, 15.2, 10.4, 5.9}

iluminação_2 = {
    'locais': locais,
    'lampadas': lampadas,
    'num_lampdas': num_lampdas,
    'testadas': testadas,
    'metros_quadrados': metros_quadrados
}
iluminação_2

{'locais': ('sala', 'cozinha', 'quarto', 'banheiro'),
 'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
 'num_lampdas': (2, 1, 1, 3),
 'testadas': {'sala': True,
  'cozinha': False,
  'quarto': False,
  'banheiro': True},
 'metros_quadrados': {5.9, 10.4, 15.2, 20.0}}

In [6]:
# Verificando os tipos de dados armazenados em cada chave do dicionário iluminação_2
print(type(iluminação_2['locais']))
print(type(iluminação_2['lampadas']))
print(type(iluminação_2['num_lampdas']))
print(type(iluminação_2['testadas']))
print(type(iluminação_2['metros_quadrados']))

<class 'tuple'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'set'>

In [7]:
# Recuperando a matriz
matrix

[[1, 2], [3, 4], [5, 6], [7, 8]]

# Editando matriz

In [8]:
# Alnterando a matriz com uma string na posição da primeira linha e primeira coluna
matrix[0][0] = "1"
matrix

[['1', 2], [3, 4], [5, 6], [7, 8]]

In [9]:
# Altreando a matriz com uma string na posição da segunda linha
matrix[1] = "iluminação_2"
matrix

[['1', 2], 'iluminação_2', [5, 6], [7, 8]]

In [10]:
# Alterando a matriz com um dicionário na posição da terceira linha
matrix.insert(4, ["iluminação_2", iluminação_2])
matrix

[['1', 2],
 'iluminação_2',
 [5, 6],
 [7, 8],
 ['iluminação_2',
  {'locais': ('sala', 'cozinha', 'quarto', 'banheiro'),
   'lampadas': ['ligada', 'desligada', 'quebrada', 'ligada'],
   'num_lampdas': (2, 1, 1, 3),
   'testadas': {'sala': True,
    'cozinha': False,
    'quarto': False,
    'banheiro': True},
   'metros_quadrados': {5.9, 10.4, 15.2, 20.0}}]]

In [11]:
import pandas as pd
import numpy as np

# Array

In [12]:
# Alterando o dicionário para um array numpy
id = 'testadas'
array = np.array(iluminação_2['locais'])
array = np.append(array, iluminação_2['lampadas'])
array = np.append(array, iluminação_2['num_lampdas'])
array = np.append(array, [
                    iluminação_2[id][list(iluminação_2[id].keys())[0]],
                    iluminação_2[id][list(iluminação_2[id].keys())[1]],
                    iluminação_2[id][list(iluminação_2[id].keys())[2]],
                    iluminação_2[id][list(iluminação_2[id].keys())[3]]
                ]
)
array = array.reshape(4, -1)
array

array([['sala', 'cozinha', 'quarto', 'banheiro'],
       ['ligada', 'desligada', 'quebrada', 'ligada'],
       ['2', '1', '1', '3'],
       ['True', 'False', 'False', 'True']], dtype='<U21')

In [13]:
# Verificando o tipo do array
type(array)

numpy.ndarray

In [14]:
# Verificando o formato do array
array.shape

(4, 4)

In [15]:
# Instanciando um vetor de números inteiros aleatórios utilizando a função randint do numpy
num_vetor = np.random.randint(0, 10, 9)
num_vetor

array([4, 0, 5, 5, 0, 5, 9, 6, 2])

In [16]:
# Instanciando uma matriz de números inteiros aleatórios utilizando a função randint do numpy
num_matrix = np.random.randint(
                    0, 
                    10,
                    size=(3, 3)
)
num_matrix

array([[3, 3, 8],
       [2, 0, 6],
       [3, 6, 0]])

In [17]:
# Intanciando um array (tensor) de números inteiros aleatórios utilizando a função randint do numpy
num_array = np.array((
    num_matrix,
    num_matrix,
    num_matrix,
))
num_array

array([[[3, 3, 8],
        [2, 0, 6],
        [3, 6, 0]],

       [[3, 3, 8],
        [2, 0, 6],
        [3, 6, 0]],

       [[3, 3, 8],
        [2, 0, 6],
        [3, 6, 0]]])

In [18]:
# Verificnaod o formato do array
num_array.shape

(3, 3, 3)

# Pandas

In [19]:
# Instanciando um DataFrame do pandas a partir da matriz de números inteiros aleatórios
df = pd.DataFrame(num_matrix)
df

   0  1  2
0  3  3  8
1  2  0  6
2  3  6  0

In [20]:
# Importando o módulo os para acessar o sistema de arquivos
import os

# Verificando os arquivos e diretórios presentes no diretório atual utilizando a função listdir do módulo os
os.listdir()

['aulas', 'data', 'exercicios', 'exercicios_resolvidos']

In [21]:
# Importando o conjunto de dados do arquivo data.csv utilizando a função read_csv do pandas
df = pd.read_csv('./data/data.csv')
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1