# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [10]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

p2 = 2.0 + 3.0 / 5.0 != 10
q2 = (p + 10.2) - 5.0 * 2.0 == 2.9
r2 = 10 <= p / q + 33.8 > 100
s2 = 5 == p / (q + r)
t2 = 33 != s * 2

print("Antes Depois")
print(p, p2)
print(q, q2)
print(r, r2)
print(s, s2)
print(t, t2)

Antes Depois
False True
True False
True False
True False
False True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [8]:
p = ('a',1,True,'b',0,False) or ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] or ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] or ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] or ['a',True,1]
t = ['a',1,True,'b',0,False] or 1
u = ['a',True,1] <= ['a',True,1] or ['a',1,True,'b',0,False]

print(p)
print(q)
print(r)
print(s)
print(t)
print(u)

('a', 1, True, 'b', 0, False)
['a', 1, True, 'b', 0, False]
['a', 1, True, 'b', 0, False]
['a', 1, True, 'b', 0, False]
['a', 1, True, 'b', 0, False]
True

In [15]:
p2 = not ('a',1,True,'b',0,False) or ('a',True,1,'b',False,0)
q2 = not ['a',1,True,'b',0,False] or ('a',True,1,'b',False,0)
r2 = not ['a',1,True,'b',0,False] or ['a',True,1,'b',False,0]
s2 = not ['a',1,True,'b',0,False] or ['a',True,1]
t2 = not ['a',1,True,'b',0,False] or 1
u2 = not ['a',True,1] <= ['a',True,1] or ['a',1,True,'b',0,False]

print(p, p2)
print(q, q2)
print(r, r2)
print(s, s2)
print(t, t2)
print(u, u2)

('a', 1, True, 'b', 0, False) ('a', True, 1, 'b', False, 0)
['a', 1, True, 'b', 0, False] ('a', True, 1, 'b', False, 0)
['a', 1, True, 'b', 0, False] ['a', True, 1, 'b', False, 0]
['a', 1, True, 'b', 0, False] ['a', True, 1]
['a', 1, True, 'b', 0, False] 1
True ['a', 1, True, 'b', 0, False]

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [18]:
import pandas as pd

df = pd.read_csv("df_aula_7.csv", index_col=0) # em vez de 'Unnamed: 0' usei apenas 0 com esse parametro
df = df.round(3)
df

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015

In [24]:
(df.iloc[1].to_list() == df.iloc[2].to_list()) or (df.iloc[3].to_list() == df.iloc[4].to_list())

False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [43]:
(df.iloc[0] >= 10).all()

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [ ]:
df.iloc[:,2].between(0, 40)

0                True
1                True
2                True
3                True
4                True
media_colunas    True
Name: 2, dtype: bool

In [47]:
df.iloc[:,2].between(0, 40).all()

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [50]:
(df.iloc[-1] > 10).all()

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [ ]:
df_filtrado = df[(df > 5) & (df < 7)]

df_filtrado

                0      1   2      3  media_linhas
0             NaN    NaN NaN    NaN           NaN
1             NaN    NaN NaN  5.893           NaN
2             NaN    NaN NaN    NaN           NaN
3             NaN    NaN NaN    NaN           NaN
4             NaN  5.893 NaN    NaN           NaN
media_colunas NaN    NaN NaN    NaN         5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

df_8 = df[(df <= 5) | (df > 7)]

df_8

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [65]:
import numpy as np

array_1 = df['3']
array_2 = df['media_linhas']

print(array_1)
print(array_2)

0                0.069
1                5.893
2                2.800
3                1.612
4                0.372
media_colunas    2.149
Name: 3, dtype: float64
0                10.050
1                 2.329
2                 1.509
3                 9.137
4                 2.050
media_colunas     5.015
Name: media_linhas, dtype: float64

In [67]:
resultado_9 = np.any((array_1 >= 2) & (array_1 <= 5))
resultado_9

np.True_

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [73]:
resultado_10 = np.all((array_1 > -1) & (array_1 < 12)) and np.all((array_2 > -1) & (array_2 < 12))
resultado_10

np.True_