In [1]:
num__1 = 4
num_2 = 2

print(num__1, num_2)

4 2

In [4]:
tupla_1 = (1, 2, 3)
tupla_2 = (1, 3, 3)

tupla_1 += tupla_2

display(tupla_1)
display(tupla_2)

(1, 2, 3, 1, 3, 3)

(1, 3, 3)

In [ ]:
lista_1 = list(tupla_1)

display(lista_1)

[1, 2, 3, 1, 3, 3]

In [7]:
lista_1[2] += 2
lista_1

[1, 2, 5, 1, 3, 3]

In [11]:
dict_1 = {
    "a": 1, 
    "b": 5 
    }

dict_2 = {
    "a": 10, 
    "bb": 3 
    }

In [12]:
dict_1.update(dict_2)

dict_1

{'a': 10, 'b': 5, 'bb': 3}

In [14]:
import numpy as np

In [20]:
array = np.array(lista_1)

array

array([1, 2, 5, 1, 3, 3])

In [ ]:
array += 2 #soma dois a todos os elementos
array

array([3, 4, 7, 3, 5, 5])

In [22]:
array *= array

array

array([ 9, 16, 49,  9, 25, 25])

In [ ]:
np.insert(arr=array, obj=1, values=100) #insere no meio

array([  9, 100,  16,  49,   9,  25,  25])

In [ ]:
np.insert(arr=np.array(['a', 'b']), obj=2, values=[0, 3])

array(['a', 'b', '0', '3'], dtype='<U1')

In [30]:
array = np.insert(arr=np.array(['a', 'b']), obj=2, values=[0, 3])[::-1]
array

array(['3', '0', 'b', 'a'], dtype='<U1')

In [32]:
array.shape

(4,)

In [ ]:
array = array.reshape(2,2)
array

array([['3', '0'],
       ['b', 'a']], dtype='<U1')

In [36]:
import pandas as pd

df = pd.DataFrame(array)
df

   0  1
0  3  0
1  b  a

In [38]:
df += df

df

    0   1
0  33  00
1  bb  aa

In [50]:
df = pd.DataFrame(
    [[1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]]
                  )

In [51]:
array_ones = np.zeros_like(df)

array_ones[1,-1] = 100

array_ones

array([[  0,   0,   0,   0],
       [  0,   0,   0, 100],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [52]:
df += array_ones

df

   0  1  2    3
0  1  1  1    1
1  1  1  1  101
2  1  1  1    1
3  1  1  1    1